export enum TN3270FieldColors {
  DEFAULT = 0,
  BLACK = 0xf0,
  BLUE = 0xf1,
  RED = 0xf2,
  PINK = 0xf3,
  GREEN = 0xf4,
  TURQUOISE = 0xf5,
  YELLOW = 0xf6,
  WHITE = 0xf7,
  INTENSIFY = 0xf8,
  DEEP_BLUE = 0xf9,
  ORANGE = 0xfa,
  PURPLE = 0xfb,
  PALE_GREEN = 0xfc,
  PALE_TURQUOISE = 0xfd,
  GRAY = 0xfe,
  BRIGHT_WHITE = 0xff,
}
